![imagen](./img/ejercicios.png)

# INFORMACIÓN DEL PROYECTO

### TÍTULO

He encontrado dos datasets diferentes que me han llamado la atencion, uno de metricas de Instagram y otro de historico de viajes de Bizkaibus.
Paso los dos para ver cual seria mas interesante para analizar, y de cual es mas viable hacer un EDA

In [7]:
#Escribe el título del proyecto en Markdown
titulo1 = "¿Qué dicen mis datos de Instagram? Un análisis de actividad y audiencia"

In [ ]:
titulo2= "Evolución de viajeros en Bizkaibus: tendencias y patrones 2024-2025"

### TEMA

# Describe brevemente el tema del proyecto en Markdown
tema1 = "Este dataset nos aporta los datos personales exportados desde Instagram, con el objetivo de entender los patrones de publicación, el crecimiento de la audiencia y el rendimiento del contenido a lo largo del tiempo."

tema2 = Bizkaibus nos ofrece varios paquetes de datos, distribuidos por trimestres con los datos de usuarios por cada una de las lineas
que tiene Bizkaibus y el número de personas viajeras por tipo de título (billete), acumulados por meses. Tenemos datos sobre que tipo de billete se utiliza y los descuentos que se ofrecen, de ahi podremos sacar por rangos de edad, quienes utilizan más el autobus, que líneas son las más frecuentadas, ¿existe temporalidad?, ha aumentado el uso respecto al año anterior?.

### HIPÓTESIS

Define aquí lo que será la hipótesis de tu proyecto.
Deberás tener más de una, pero tu proyecto lo harás teniendo una principal hipótesis.

#### Hipótesis Instagram
1. hipotesis_1 = "Hay días de la semana y franjas horarias en los que se publica con más frecuencia"
2. hipotesis_2 = "El crecimiento de seguidores no es lineal — hay meses con picos de crecimiento que coinciden con mayor actividad"
3. hipotesis_3 = "Las interacciones de tipo "compartir" y "guardar" superan a los comentarios, lo que indica contenido de valor pero poca conversación"

#### Hipótesis Bizkaibus
1. hipotesis_1 = "Los títulos de transporte bonificados para jóvenes representan una proporción significativa del total de viajeros."
2. hipotesis_2 = "Hay meses con más afluencia que otros"
3. hipotesis_3 = "Las líneas que más crecen son las que conectan con Bilbao"
4. hipotesis_4 = "Las ayudas al transporte han impulsado el uso del autobus"

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

Incluye aquí una vista del dataset o datasets de los que partirás para poder evaluar tu hipótesis. <br>
También incluye el origen de estos datos y su fuente.

In [ ]:
import pandas as pd

instagram = pd.DataFrame()
fuente_1 = "https://www.kaggle.com/datasets/kundanbedmutha/instagram-analytics-dataset"


bizkaibus = pd.DataFrame()
fuente_2 = "https://www.opendatabizkaia.eus/es/catalogo/bizkaibus"
'''
La info viene por trimestres en datasets de 285 filas con 42 columnas. Voy a juntar los trimestres del 2025 y 2024 para el análisis 
Por tanto quedarian 2280 filas de datos con 42 columnas.(Sí son muchas, sigamos leyendo)
Muchas de las columnas son prescindibles, algunas no tienen datos y otras son de variables que se pueden resumir en una.
En el caso de que sean pocas líneas, hay registros hasta 2020 que se pueden añadir. Seguramenta añadiré todos los registros 
disponibles, para verla evolucion desde la introduccion de las Ayudas al Transporte bonificadas al 50%

'''
fuente_3 = "https://www.opendatabizkaia.eus/es/catalogo/bizkaibus-expediciones-refuerzos/recurso/expediciones-realizadas-2025"
            "https://www.opendatabizkaia.eus/es/catalogo/bizkaibus-expediciones-refuerzos"
'''
Esta ultima fuente son las expediciones de los autobuses, es decir de cada line cuantos viajes han hecho los autobuses, 
por epocas del año, etc.
Si hago este EDA y veo que no se me complica, me planteare añadir este dataset para analizar algun dato extra.

'''

Muestra mediante un head() los principales datasets con los que vas a trabajar

In [2]:
import pandas as pd
import numpy as np

In [4]:
#INSTAGRAM

instagram = pd.read_csv("Instagram_Analytics.csv")
instagram.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,...,5,7,34,4327,6230,0.0385,899,100,7,medium
1,IG0000002,20,creator,31095,image,Fitness,Hashtags,1,2025-08-15 15:00:00,2025-08-15,...,10,21,68,7451,8268,0.0663,805,122,5,viral
2,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,...,2,1,22,1639,2616,0.0531,758,115,8,high
3,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,...,0,7,0,2877,3171,0.0309,402,115,7,medium
4,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,...,8,5,21,5350,8503,0.0221,155,112,9,low

In [6]:
#BIZKAIBUS

bizkaibus = pd.read_csv("2025_biz_sept.csv")
bizkaibus.head()

,_id,EKITALDIA/EJERCICIO,HILABETE/MES,ZENBAKIA/CODIGO,LERROA/LINEA,CREDITRANS/CREDITRANS,CREDITRANS F20/CREDITRANS F20,CREDITRANS F50/CREDITRANS F50,GIZATRANS/GIZATRANS,GIZATRANS 20/GIZATRANS 20,...,BAT BEREZI F50/BAT BEREZI F50,OHIKOA/OCASIONAL,FAMILIA UGARIA/FAMILIA NUMEROSA,6 URTETIK BEHERAKOAK/MENORES DE 6 ANOS,ITSU-MUP-EN GIDARI-LAGUN/ACOMPANANTE INVIDENTE-PMRS,ITSU-MUPEN DOAKO GIDARILAGUN/ACOMPANANTE GRATIS INVIDENTE-PMRS,METROA/METRO,T.M MATXURA/PUP AVERIADO,ENPRESA/EMPRESA,GUZTIRA/TOTAL
0,1,2025,7,A2610,GALDAKAO - UPV/EHU,1146,25,9,125,1,...,0,16,0,13,0,0,0,0,12,1815
1,2,2025,7,A2611,UGAO MIRABALLES - BASAURI - ETXEBARRI - UPV/EHU,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,2025,7,A3613,BILBAO - UGAO MIRABALLES - OROZKO,22870,409,24,10470,15,...,0,944,0,1109,71,0,0,0,387,40927
3,4,2025,7,A3622,BILBAO - BASAURI - Artunduaga - San Miguel -ZA...,8423,146,49,2330,25,...,0,305,0,325,4,0,0,0,155,14350
4,5,2025,7,A3631,BILBAO - GALDAKAO - LARRABETZU,16824,233,69,5396,17,...,0,691,0,504,6,0,0,0,369,29299