# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [19]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [10]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   float64
 5   total               4622 non-null   float64
 6   precio_uni          4622 non-null   float64
dtypes: float64(3), int64(2), str(2)
memory usage: 252.9 KB

In [ ]:
print(chipo.dtypes)

In [20]:
#Convertir a float
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

#Buscar el maximo

chipo["precio_unitario"] = chipo["item_price"]/ chipo["quantity"]  
chipo   
idx = chipo['precio_unitario'].idxmax()       
chipo.iloc[idx]

order_id                                                            123
quantity                                                              2
item_name                                              Steak Salad Bowl
choice_description    [Tomatillo Red Chili Salsa, [Black Beans, Chee...
item_price                                                        23.78
precio_unitario                                                   11.89
Name: 281, dtype: object

### Step 4. How many products cost more than $10.00?

In [28]:
chipo[(chipo.precio_unitario > 10.00)]

,order_id,quantity,item_name,choice_description,item_price,precio_unitario
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98,10.98
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75,11.75
...,...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25,11.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25

In [37]:
chipo[chipo["precio_unitario"] > 10.00] ["item_name"].nunique()

25

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [42]:
len(chipo[chipo["precio_unitario"] > 10.00] ["order_id"].unique())

787

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [43]:
chipo['total'] = chipo['quantity'] * chipo['item_price']
pedidos = chipo.groupby('order_id')['total'].sum()
len(pedidos[pedidos > 10.00])

1834

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [57]:
adios = chipo[chipo["item_price"] > 10.00] ["order_id"].nunique()
print(adios)

863

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [62]:
result = chipo[['item_name', 'precio_unitario']].drop_duplicates().reset_index(drop=True)

result.head(25)

                                item_name  precio_unitario
0            Chips and Fresh Tomato Salsa             2.39
1                                    Izze             3.39
2                        Nantucket Nectar             3.39
3   Chips and Tomatillo-Green Chili Salsa             2.39
4                            Chicken Bowl             8.49
5                            Chicken Bowl            10.98
6                           Side of Chips             1.69
7                           Steak Burrito            11.75
8                        Steak Soft Tacos             9.25
9                           Steak Burrito             9.25
10                    Chips and Guacamole             4.45
11                   Chicken Crispy Tacos             8.75
12                     Chicken Soft Tacos             8.75
13                           Chicken Bowl            11.25
14                        Chicken Burrito             8.49
15                            Canned Soda             1.09
16                           Chicken Bowl             8.75
17                       Barbacoa Burrito             8.99
18                        Chicken Burrito            10.98
19                       Carnitas Burrito             8.99
20                          Steak Burrito             8.99
21                          Carnitas Bowl             8.99
22                          Bottled Water             1.09
23  Chips and Tomatillo Green Chili Salsa             2.95
24                          Barbacoa Bowl            11.75

### Step 6. Sort by the name of the item

In [59]:
ordenado = chipo.sort_values("item_name")
print(ordenado)

      order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink
341        148         1  6 Pack Soft Drink
1849       749         1  6 Pack Soft Drink
1860       754         1  6 Pack Soft Drink
2713      1076         1  6 Pack Soft Drink
...        ...       ...                ...
2384       948         1  Veggie Soft Tacos
781        322         1  Veggie Soft Tacos
2851      1132         1  Veggie Soft Tacos
1699       688         1  Veggie Soft Tacos
1395       567         1  Veggie Soft Tacos

                                     choice_description  item_price  \
3389                                        [Diet Coke]       12.98
341                                         [Diet Coke]        6.49
1849                                             [Coke]        6.49
1860                                        [Diet Coke]        6.49
2713                                             [Coke]        6.49
...                                                 ...         ...
2384  [Roasted Chili Corn Salsa, [Fajita Vegetables,...        8.75
781   [Fresh Tomato Salsa, [Black Beans, Cheese, Sou...        8.75
2851  [Roasted Chili Corn Salsa (Medium), [Black Bea...        8.49
1699  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.25
1395  [Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...        8.49

      precio_unitario  total
3389             6.49  25.96
341              6.49   6.49
1849             6.49   6.49
1860             6.49   6.49
2713             6.49   6.49
...               ...    ...
2384             8.75   8.75
781              8.75   8.75
2851             8.49   8.49
1699            11.25  11.25
1395             8.49   8.49

[4622 rows x 7 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [68]:
print(chipo["item_price"].max())

chipo[["item_name","quantity","item_price"]][chipo["item_price"] == chipo["item_price"].max()]

44.25

                         item_name  quantity  item_price
3598  Chips and Fresh Tomato Salsa        15       44.25

In [73]:
caro = chipo.sort_values("item_price", ascending=False)
cantidad = caro.iloc[0]["quantity"]
print(cantidad)

caro.head()

15

,order_id,quantity,item_name,choice_description,item_price,precio_unitario,total
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,2.95,663.75
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25,11.75,105.75
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00,8.75,140.00
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00,8.75,140.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75,11.25,101.25

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [ ]:
count = chipo['item_name'].value_counts()['Veggie Salad Bowl']
print(count)

18

### Step 9. How many times did someone order more than one Canned Soda?

In [75]:
chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]["order_id"].nunique()

18