# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [3]:
print(chipo.dtypes)

order_id              int64
quantity              int64
item_name               str
choice_description      str
item_price              str
dtype: object

In [4]:
#Convertir a float
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

#Buscar el maximo
idx = chipo['item_price'].idxmax()       
chipo.iloc[idx]

order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
Name: 3598, dtype: object

### Step 4. How many products cost more than $10.00?

In [5]:
chipo.item_price > 10.00
chipo[(chipo.item_price > 10.00)]

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [6]:
len(chipo[chipo['item_price'] > 10.00])

1130

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [7]:
chipo['total'] = chipo['quantity'] * chipo['item_price']
pedidos = chipo.groupby('order_id')['total'].sum()
len(pedidos[pedidos > 10.00])

1834

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [8]:
chipo['total'] = chipo['quantity'] * chipo['item_price']
len(chipo[chipo['total'] > 10.00])
items = chipo.groupby('item_name')['total'].sum()
print(items)

item_name
6 Pack Soft Drink                         369.93
Barbacoa Bowl                             672.36
Barbacoa Burrito                          894.75
Barbacoa Crispy Tacos                     138.71
Barbacoa Salad Bowl                       106.40
Barbacoa Soft Tacos                       250.46
Bottled Water                             649.18
Bowl                                       74.00
Burrito                                    44.40
Canned Soda                               191.84
Canned Soft Drink                         603.75
Carnitas Bowl                             830.71
Carnitas Burrito                          616.33
Carnitas Crispy Tacos                      95.94
Carnitas Salad                              8.99
Carnitas Salad Bowl                        66.34
Carnitas Soft Tacos                       375.94
Chicken Bowl                             8044.63
Chicken Burrito                          6387.06
Chicken Crispy Tacos                      524.11
Chicken Salad                              81.09
Chicken Salad Bowl                       1506.25
Chicken Soft Tacos                       1199.01
Chips                                     580.34
Chips and Fresh Tomato Salsa             1033.96
Chips and Guacamole                      2475.62
Chips and Mild Fresh Tomato Salsa           3.00
Chips and Roasted Chili Corn Salsa         73.75
Chips and Roasted Chili-Corn Salsa         43.02
Chips and Tomatillo Green Chili Salsa     144.55
Chips and Tomatillo Red Chili Salsa       159.30
Chips and Tomatillo-Green Chili Salsa      88.43
Chips and Tomatillo-Red Chili Salsa        93.21
Crispy Tacos                               14.80
Izze                                       67.80
Nantucket Nectar                          111.87
Salad                                      14.80
Side of Chips                             290.68
Steak Bowl                               2479.81
Steak Burrito                            4236.13
Steak Crispy Tacos                        375.32
Steak Salad                                35.66
Steak Salad Bowl                          391.15
Steak Soft Tacos                          554.55
Veggie Bowl                               901.95
Veggie Burrito                           1002.27
Veggie Crispy Tacos                         8.49
Veggie Salad                               50.94
Veggie Salad Bowl                         182.50
Veggie Soft Tacos                          90.94
Name: total, dtype: float64

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [15]:
chipo['precio_uni'] = chipo['item_price'] / chipo['quantity']

result = chipo[['item_name', 'unit_price']].drop_duplicates().reset_index(drop=True)

print(result)

                                 item_name  unit_price
0             Chips and Fresh Tomato Salsa        2.39
1                                     Izze        3.39
2                         Nantucket Nectar        3.39
3    Chips and Tomatillo-Green Chili Salsa        2.39
4                             Chicken Bowl        8.49
..                                     ...         ...
134                          Chicken Salad        8.19
135                           Chicken Bowl        8.50
136                    Chips and Guacamole        4.25
137                                  Chips        1.99
138                          Barbacoa Bowl       11.49

[139 rows x 2 columns]

### Step 6. Sort by the name of the item

In [18]:
ordenado = chipo.sort_values("item_name")
print(ordenado)

      order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink
341        148         1  6 Pack Soft Drink
1849       749         1  6 Pack Soft Drink
1860       754         1  6 Pack Soft Drink
2713      1076         1  6 Pack Soft Drink
...        ...       ...                ...
2384       948         1  Veggie Soft Tacos
781        322         1  Veggie Soft Tacos
2851      1132         1  Veggie Soft Tacos
1699       688         1  Veggie Soft Tacos
1395       567         1  Veggie Soft Tacos

                                     choice_description  item_price  total  \
3389                                        [Diet Coke]       12.98  25.96
341                                         [Diet Coke]        6.49   6.49
1849                                             [Coke]        6.49   6.49
1860                                        [Diet Coke]        6.49   6.49
2713                                             [Coke]        6.49   6.49
...                                                 ...         ...    ...
2384  [Roasted Chili Corn Salsa, [Fajita Vegetables,...        8.75   8.75
781   [Fresh Tomato Salsa, [Black Beans, Cheese, Sou...        8.75   8.75
2851  [Roasted Chili Corn Salsa (Medium), [Black Bea...        8.49   8.49
1699  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.25  11.25
1395  [Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...        8.49   8.49

      unit_price  precio_uni
3389        6.49        6.49
341         6.49        6.49
1849        6.49        6.49
1860        6.49        6.49
2713        6.49        6.49
...          ...         ...
2384        8.75        8.75
781         8.75        8.75
2851        8.49        8.49
1699       11.25       11.25
1395        8.49        8.49

[4622 rows x 8 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [20]:
caro = chipo.loc[chipo['item_price'].idxmax()]
print(caro[['item_name', 'item_price', 'quantity']])

item_name     Chips and Fresh Tomato Salsa
item_price                           44.25
quantity                                15
Name: 3598, dtype: object

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [21]:
count = chipo['item_name'].value_counts()['Veggie Salad Bowl']
print(count)

18

### Step 9. How many times did someone order more than one Canned Soda?

In [24]:
count = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]
print(len(count))

20